// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD_C6fguB3dv9l6bA57hFfoxE4nnSNAoQ',
    appId: '1:233003246878:web:69fad14fdeb03b906d950f',
    messagingSenderId: '233003246878',
    projectId: 'pomodorocommit',
    authDomain: 'pomodorocommit.firebaseapp.com',
    storageBucket: 'pomodorocommit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaji1YVFDjZw91FYhXc5FV1IaHLvtLY4o',
    appId: '1:233003246878:android:e8c8ceef2e0463d36d950f',
    messagingSenderId: '233003246878',
    projectId: 'pomodorocommit',
    storageBucket: 'pomodorocommit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV3WxzfckGNWKHpckHRxkfXC5AakxgKcM',
    appId: '1:233003246878:ios:ff98b47646212e126d950f',
    messagingSenderId: '233003246878',
    projectId: 'pomodorocommit',
    storageBucket: 'pomodorocommit.firebasestorage.app',
    iosBundleId: 'com.example.projetodia4do7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV3WxzfckGNWKHpckHRxkfXC5AakxgKcM',
    appId: '1:233003246878:ios:ff98b47646212e126d950f',
    messagingSenderId: '233003246878',
    projectId: 'pomodorocommit',
    storageBucket: 'pomodorocommit.firebasestorage.app',
    iosBundleId: 'com.example.projetodia4do7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD_C6fguB3dv9l6bA57hFfoxE4nnSNAoQ',
    appId: '1:233003246878:web:91b938190287d4486d950f',
    messagingSenderId: '233003246878',
    projectId: 'pomodorocommit',
    authDomain: 'pomodorocommit.firebaseapp.com',
    storageBucket: 'pomodorocommit.firebasestorage.app',
  );
}
